import 'package:emplog/model/db/attendance.dart';
import 'package:emplog/model/outlet.dart';
import 'package:emplog/utils/constants.dart';

double fakeLatitude = 23.874187586642176;
double fakeLongitude = 90.40443741117636;

List<Outlet> outlets = [
  Outlet(
      guid: "1",
      branch: "প্রগতি সরনী",
      branchType: "Jamuna Electronics Showroom",
      address: "193 প্রগতি সরনী, ঢাকা 1229",
      logo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTYCpR-NGr1fIUtcJ36spbE49T9MRFE3Qnt3w&usqp=CAU",
      latitude: 23.8130958,
      longitude: 90.4211896,
      contactPerson: "Jamil Sorwer",
      phone: "01777-778595"),
  Outlet(
      guid: "2",
      branch: "Jamuna Future Park",
      branchType: "Jamuna Electronics & Automobiles Limited",
      address: "Ka-244, Progoti Soroni Kuril Jamuna Future Park 6th Flor, Dhaka 1229",
      logo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRGrKxS_3XyI7QhdFyyZM0qRalJVUj33_VJUQ&usqp=CAU",
      latitude: 23.8134905,
      longitude: 90.3891376,
      contactPerson: "Rashid Ahmed",
      phone: ""),
  Outlet(
      guid: "3",
      branch: "টঙ্গী",
      branchType: "Jamuna Electronics & Automobiles",
      address: "Tongi",
      logo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRGrKxS_3XyI7QhdFyyZM0qRalJVUj33_VJUQ&usqp=CAU",
      latitude: 23.8996512,
      longitude: 90.4071998,
      contactPerson: "Shafik Bari",
      phone: "+8801911707591"),
  Outlet(
      guid: "4",
      branch: "Gazipur",
      branchType: "Jamuna Electronics Gazipur Plaza",
      address: "Gazipur",
      logo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRGrKxS_3XyI7QhdFyyZM0qRalJVUj33_VJUQ&usqp=CAU",
      latitude: 23.8769384,
      longitude: 90.3889525,
      contactPerson: "Ahmed Malik",
      phone: "+8801766694341"),
  Outlet(
      guid: "5",
      branch: "Pallabi",
      branchType: "Jamuna Showroom",
      address: "Sujat Mansion, Pallabi, Mirpur 12, Dhaka 1216",
      logo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRGrKxS_3XyI7QhdFyyZM0qRalJVUj33_VJUQ&usqp=CAU",
      latitude: 23.8295041,
      longitude: 90.3700761,
      contactPerson: "Kiron Patowary",
      phone: ""),
];

List<Attendance> attendances = [
  Attendance(
      guid: "1",
      dateTime: "2021-03-07 20:01:00",
      latitude: fakeLatitude,
      longitude: fakeLongitude,
      location: "প্রগতি সরনী",
      event: AttendanceType.Out,
      duration: "10 hours",
      picture: ""),
  Attendance(
      guid: "2",
      dateTime: "2021-03-07 18:22:00",
      latitude: fakeLatitude,
      longitude: fakeLongitude,
      location: "Vai Vai store",
      event: AttendanceType.ShopVisit,
      duration: "10 hours",
      picture: ""),
  Attendance(
      guid: "3",
      dateTime: "2021-03-07 13:42:00",
      latitude: fakeLatitude,
      longitude: fakeLongitude,
      location: "General Electronic store",
      event: AttendanceType.ShopVisit,
      duration: "10 hours",
      picture: ""),
  Attendance(
      guid: "4",
      dateTime: "2021-03-07 11:07:00",
      latitude: fakeLatitude,
      longitude: fakeLongitude,
      location: "Akib Electronic heaven",
      event: AttendanceType.ShopVisit,
      duration: "10 hours",
      picture: ""),
  Attendance(
      guid: "5",
      dateTime: "2021-03-07 08:02:00",
      latitude: fakeLatitude,
      longitude: fakeLongitude,
      location: "Jamuna Future Park Outlet",
      event: AttendanceType.In,
      duration: "10 hours",
      picture: ""),
  Attendance(
      guid: "6",
      dateTime: "2021-03-06 19:51:00",
      latitude: fakeLatitude,
      longitude: fakeLongitude,
      location: "প্রগতি সরনী",
      event: AttendanceType.Out,
      duration: "09 hours",
      picture: ""),
  Attendance(
      guid: "7",
      dateTime: "2021-03-06 18:22:00",
      latitude: fakeLatitude,
      longitude: fakeLongitude,
      location: "Vai Vai store",
      event: AttendanceType.ShopVisit,
      duration: "10 hours",
      picture: ""),
  Attendance(
      guid: "8",
      dateTime: "2021-03-06 13:42:00",
      latitude: fakeLatitude,
      longitude: fakeLongitude,
      location: "General Electronic store",
      event: AttendanceType.ShopVisit,
      duration: "10 hours",
      picture: ""),
  Attendance(
      guid: "9",
      dateTime: "2021-03-06 11:07:00",
      latitude: fakeLatitude,
      longitude: fakeLongitude,
      location: "Akib Electronic heaven",
      event: AttendanceType.ShopVisit,
      duration: "10 hours",
      picture: ""),
  Attendance(
      guid: "10",
      dateTime: "2021-03-06 10:02:00",
      latitude: fakeLatitude,
      longitude: fakeLongitude,
      location: "Jamuna Future Park Outlet",
      event: AttendanceType.In,
      duration: "9 hours",
      picture: ""),
];
